#!/bin/bash

#tag [db] [file] [tar] [mysql] [backup] [bk]

OBJ=/root/backup/incr
TODAY=`date +%Y%m%d`
#array_name=(
#       "/home/www/traumplanet"
#       "/home/www/traumplanet-dev"
#       "/home/www/tplanit-dev"
#       "/home/www/tplanit"
#       "/home/www/traumguard"
#       "/home/www/traum"
#       "/home/www/mktraum"
#       "/home/www/startgd"
#       "/home/www/traumguard-detail"
#       "/home/www/traumguard-stella" )

#array_length=${#array_name[@]}

cd $OBJ
#mkdir $TODAY
#cd $TODAY

# if size gt 60, then specity file's deleted but else, backup
#DFSIZE=`df -h | grep sda2 | awk '{print $5}' | awk -F % '{print $1}'`
#if [ $DFSIZE -gt 60 ]
#then
#       cd $OBJ
#       find /root/backup/incr -type d -mtime +4 -exec rm -f {} \;
#else

#       for (( j=0; j<$array_length; j++ )); do
#                       FILENAME=`echo ${array_name[$j]} | awk -F / '{print (\$4)}'`
#                       MOD_NAME=`echo ${array_name[$j]}`
#                       tar cvpzf $FILENAME.tar $MOD_NAME
#       done
#fi

# if size is high than 95, then specity file's deleted
CHECKSIZE=`df -h | grep sda6 | awk '{print $5}' | awk -F % '{print $1}'`
if [ $CHECKSIZE -gt 85 ]
        then
                find /root/backup/incr -type f -mtime +30 -exec rm {} \;
        else
                mysqldump -umktptraumplanet -ptptm95250319 traummobile > /root/backup/incr/traummobile.$TODAY.sql
fi

//  위는 데일리 백업



#!/bin/bash

#tag [db] [file] [tar] [mysql] [backup] [bk]

TODAY=`date +%Y%m%d`
OBJ=/root/backup/full
BK_PATH=/home/www/

cd $OBJ
mkdir $TODAY
cd $TODAY
DFSIZE=`df -h | grep sda2 | awk '{print $5}' | awk -F % '{print $1}'`


if [ $DFSIZE -gt 60 ]
        then
    find /root/backup/full -type d -mtime +3 -exec rm -rf {} \;

                if [ 60 -gt $DFSIZE ]
                then
        cd $OBJ
                tar cvpzf BKall.tar $BK_PATH
                fi
else
        tar cvpzf BKall.tar $BK_PATH

fi

// 위는 풀백업 
